name: 🐛 Bug Report
description: Report something that's broken
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: "Brief description of the bug"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
