name: "🐛 Bug Report"
description: "Report something that's broken"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: steps
    attributes:
      label: "Description"
      description: "Describe the bug and provide details in steps"
      placeholder: |
        1. Batch name...
        2. Year ...
        3. Timing (09-10am)
        4. Course Code
    validations:
      required: true
