name: 🚀 Feature Request
description: Suggest an idea
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: input
    id: summary
    attributes:
      label: What's the feature?
      placeholder: "e.g., Add retry button in drawer"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature needed?
  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
