name: ❓ Question
description: Ask a question about this project
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your Question
      placeholder: "e.g., How are minors filtered out in the timetable?"
    validations:
      required: true
