name: Update Timetable

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch: # Manual trigger allowed

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Send PUT request with JSON password
        env:
          PASSWORD: ${{ secrets.UPDATE_KEY }}
        run: |
          curl -X PUT https://juit-timetable.vercel.app/api/set \
            -H "Content-Type: application/json" \
            -d "{\"password\": \"$PASSWORD\"}"

